### ISSUE TITLE
Threading problem in multiprocess class in windows

### ISSUE THREAD

**Issue by rithgroove** [rithgroove/Epidemicon#18]
So the current version apparently doesn't work in windows. Probably this problem caused by difference in how the OS implement forking technique which in turns affect the pickling of objects.

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\threading.py", line 932, in _bootstrap_inner
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>     self.run()
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\multiprocessing\spawn.py", line 116, in spawn_main
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\threading.py", line 870, in run
>     exitcode = _main(fd, parent_sentinel)
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\multiprocessing\spawn.py", line 126, in _main
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\admin\Desktop\Sim-Project\Epidemicon\lib\Renderer\Controller.py", line 114, in run_auto
>     self = reduction.pickle.load(from_parent)
> EOFError: Ran out of input
>     self.model.step(stepSize=self.view.steps_to_advance)
>   File "C:\Users\admin\Desktop\Sim-Project\Epidemicon\lib\Simulation\Simulator.py", line 230, in step
>     thread.start()
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\multiprocessing\process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\multiprocessing\context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\multiprocessing\context.py", line 327, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Users\admin\anaconda3\envs\epidemicon\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> RecursionError: maximum recursion depth exceeded while pickling an object

My idea to fix is to implement pickle "getstate" method in some classes so that the threading still works and doesn't screws up the whole project. But this is a major fix, so it'll take times to develop the fix for this issue. 

@jair-pereira mentioned to me that he was having the same problem (I think he use mac?). That's why, for now, I assume the code only works well in Linux.

**Comment by jair-pereira** [comment]
I've tried only on Windows. If the problem is really how the fork is done, it should run on Mac.

I'll test it later and I'll get back to you.

**Comment by rithgroove** [comment]
One thing we could do is to set if case for different os for quick fix. The downside is that there'll be no threading for other OS than Linux until the major fix is done.

**Comment by jair-pereira** [comment]
I tried on mac and I got the same error: 
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while pickling an object

It seems to me that it is a problem of an object's instance referencing another (maybe cycle), causing a many recursive calls when pickling to use multiprocessing.
